import type { StoryDef } from './types';

export const STORIES: StoryDef[] = [
  {
  id: 'tutorial-01',
  title: 'Introduction',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 4,
    mountains: ['0,1', '0,2'],
    playerStart: [{ col: 2 }, { col: 3 }],
    aiStart: [{ col: 2 }],
  },
  productionPointsPerTurn: 4,
},
{
  id: 'tutorial-02',
  title: 'Introduction — Tanks',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 5,
    mountains: ['0,1', '3,1', '3,2', '3,3'],
    playerStart: [{ col: 0, unitTypeId: 'tank' }, { col: 2, unitTypeId: 'tank' }],
    aiStart: [{ col: 1 }],
  },
  productionPointsPerTurn: 4,
},
{
  id: 'tutorial-03',
  title: 'Introduction — Artillery',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 5,
    mountains: ['0,1', '3,1', '3,2', '3,3'],
    playerStart: [{ col: 0, unitTypeId: 'artillery' }, { col: 2, unitTypeId: 'tank' }],
    aiStart: [{ col: 1 }, { col: 2 }],
  },
  productionPointsPerTurn: 8,
},
{
  id: 'ww2-01',
  title: 'Citadel',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-02',
  title: 'Barbarossa',
  description: 'Description.',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-03',
  title: 'Bastion',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-04',
  title: 'Breakout',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-05',
  title: 'Crossroads',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-06',
  title: 'Ironwall',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-07',
  title: 'Anvil',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
}
];

export function getStoryById(id: string): StoryDef | undefined {
  return STORIES.find(s => s.id === id);
}
