import type { StoryDef } from './types';

export const STORIES: StoryDef[] = [
  {
  id: 'tutorial-01',
  scenario: 'tutorial',
  title: 'Introduction',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: 'tutorial',

  productionPointsPerTurnAi: 4,
},
{
  id: 'tutorial-02',
  title: 'Introduction — Tanks',
  description: 'Description.',
  scenario: 'tutorial',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: 'tutorial',

  productionPointsPerTurn: 20,
},
{
  id: 'tutorial-03',
  scenario: 'tutorial',
  title: 'Introduction — Artillery',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: 'tutorial',

  productionPointsPerTurnAi: 8,
},
{
  id: 'tutorial-04',
  title: 'Learn Conquest mode',
  description: 'Description.',
  scenario: 'tutorial',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: 'tutorial',

  productionPointsPerTurn: 20,
  conquestPointsPlayer: 8,
  conquestPointsAi: 8,
},
{
  id: 'tutorial-05',
  title: 'Learn Breakthrough mode',
  description: 'Description.',
  scenario: 'tutorial',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  map: 'tutorial',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 12,
},
{
  id: 'tutorial-06',
  title: 'Defend in Breakthrough',
  description: 'Description.',
  scenario: 'tutorial',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  breakthroughPlayer1Role: 'defender',
  map: 'tutorial',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 12,
  breakthroughAttackerStartingPP: 20,
},
{
  id: 'ww2-01',
  scenario: 'ww2us',
  title: 'Citadel',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 8,
},
{
  id: 'ww2-02',
  scenario: 'ww2us',
  title: 'Barbarossa',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 15,
},
{
  // Domination — 6×8 portrait
  // Theme: Force through a central mountain chokepoint. Side walls funnel all
  // combat into the two-hex gap in the middle of the map.
  id: 'ww2-04',
  scenario: 'ww2us',
  title: 'Breakout',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 15,
},
{
  // Conquest — 6×7 portrait
  // Theme: Two control points mark the crossroads junction. Mountains on the
  // flanks funnel both sides toward the contested centre.
  id: 'ww2-05',
  scenario: 'ww2us',
  title: 'Crossroads',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  conquestPointsPlayer: 10,
  conquestPointsAi: 10,
  productionPointsPerTurn: 20,
},
{
  // Domination — 7×7 square
  // Theme: Crack a heavily fortified defensive line. Two parallel mountain
  // ridges (rows 2 and 4) form the "iron wall"; only the flanks are open.
  id: 'ww2-06',
  scenario: 'ww2us',
  title: 'Ironwall',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  // Breakthrough — 6×8 portrait, player is attacker (south)
  // Theme: The anvil falls — a hammer-blow assault through three sectors.
  // Mountains guard the flanks; the attacker drives up the central corridor.
  id: 'ww2-07',
  scenario: 'ww2us',
  title: 'Anvil',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  map: '02',

  breakthroughPlayer1Role: 'attacker',
  breakthroughSectorCount: 3,
  breakthroughAttackerStartingPP: 180,
  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 16,
},
{
  id: 'ww2-08',
  title: 'Eisenfaust',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-09',
  title: 'Sturmwind',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  // Domination — 5×7 portrait
  // Theme: Dense bocage terrain. Scattered mountains create a maze, forcing
  // flanking and careful path-finding through the hedgerows.
  id: 'ww2-16',
  scenario: 'ww2us',
  title: 'Hedgerow',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-17',
  scenario: 'ww2us',
  title: 'Liberation',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 16,
},
{
  id: 'ww2-18',
  scenario: 'ww2us',
  title: 'Bridgehead',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  // Breakthrough — 5×8 portrait, player is attacker (south)
  // Theme: Concentrated armoured thrust. A narrow front forces the spearhead
  // through successive defensive layers — speed is everything.
  id: 'ww2-19',
  scenario: 'ww2us',
  title: 'Spearhead',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  map: '02',

  breakthroughPlayer1Role: 'attacker',
  breakthroughSectorCount: 3,
  breakthroughAttackerStartingPP: 160,
  productionPointsPerTurn: 20,
  productionPointsPerTurnAi: 20,
},
{
  id: 'ww2-20',
  title: 'Frostbite',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  breakthroughAttackerStartingPP: 80,
  breakthroughPlayer1Role: 'defender',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-21',
  title: 'Dämmerung',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
  breakthroughAttackerStartingPP: 100,
},
{
  id: 'ww2-22',
  title: 'Nordlicht',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-23',
  title: 'Festung',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-24',
  title: 'Storm of Steel',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  breakthroughPlayer1Role: 'defender',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-25',
  title: 'Wetterleuchten',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-26',
  title: 'Horseshoe',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-27',
  title: 'Revenge',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-28',
  title: 'Deadwater',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-29',
  title: 'Grimwall',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'ru-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-30',
  title: 'Hollow March',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-31',
  title: 'Coldspire',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-32',
  title: 'Stonegate',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-33',
  title: 'Blackfen',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-34',
  title: 'Bitter Frost',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-35',
  title: 'Wraithhold',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-36',
  title: 'Saltmarsh',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-37',
  title: 'Greymantle',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-38',
  title: 'Wolfmere',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-39',
  title: 'Ironveil',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-40',
  title: 'Ashground',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-43',
  title: 'The King Tiger',
  description: 'Description.',
  scenario: 'ww2de',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-41',
  title: 'Dead Zone',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-42',
  title: 'Flat Land',
  description: 'Description.',
  scenario: 'ww2ru',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-44',
  title: 'The blind spot',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-45',
  title: 'Wraithhold',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'conquest',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-46',
  title: 'Saltmarsh',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
},
{
  id: 'ww2-47',
  title: 'Blackfen',
  description: 'Description.',
  scenario: 'ww2jp',
  unitPackage: 'jp-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'breakthrough',
  map: '02',

  productionPointsPerTurn: 20,
}
];

export function getStoryById(id: string): StoryDef | undefined {
  return STORIES.find(s => s.id === id);
}
