import type { StoryDef } from './types';

export const STORIES: StoryDef[] = [
  {
  id: 'tutorial-01',
  scenario: 'tutorial',
  title: 'Introduction',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 4,
    mountains: ['0,1', '0,2'],
    playerStart: [{ col: 2 }, { col: 3 }],
    aiStart: [{ col: 2 }],
  },
  productionPointsPerTurn: 4,
},
{
  id: 'tutorial-02',
  scenario: 'tutorial',
  title: 'Introduction — Tanks',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 5,
    mountains: ['0,1', '3,1', '3,2', '3,3'],
    playerStart: [{ col: 0, unitTypeId: 'tank' }, { col: 2, unitTypeId: 'tank' }],
    aiStart: [{ col: 1 }],
  },
  productionPointsPerTurn: 4,
},
{
  id: 'tutorial-03',
  scenario: 'tutorial',
  title: 'Introduction — Artillery',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 4,
    rows: 5,
    mountains: ['0,1', '3,1', '3,2', '3,3'],
    playerStart: [{ col: 0, unitTypeId: 'artillery' }, { col: 2, unitTypeId: 'tank' }],
    aiStart: [{ col: 1 }, { col: 2 }],
  },
  productionPointsPerTurn: 8,
},
{
  id: 'ww2-01',
  scenario: 'ww2us',
  title: 'Citadel',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-02',
  scenario: 'ww2us',
  title: 'Barbarossa',
  description: 'Description.',
  unitPackage: 'ru-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-03',
  scenario: 'ww2us',
  title: 'Bastion',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-04',
  scenario: 'ww2us',
  title: 'Breakout',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-05',
  scenario: 'ww2us',
  title: 'Crossroads',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-06',
  scenario: 'ww2us',
  title: 'Ironwall',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-07',
  scenario: 'ww2us',
  title: 'Anvil',
  description: 'Description.',
  unitPackage: 'us-ww2',
  unitPackagePlayer2: 'de-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-08',
  scenario: 'ww2de',
  title: 'Sturmwind',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-09',
  scenario: 'ww2de',
  title: 'Dämmerung',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-10',
  scenario: 'ww2de',
  title: 'Wacht',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-11',
  scenario: 'ww2de',
  title: 'Nordlicht',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-12',
  scenario: 'ww2de',
  title: 'Donnerschlag',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-13',
  scenario: 'ww2de',
  title: 'Abendstern',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-14',
  scenario: 'ww2de',
  title: 'Festung',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
},
{
  id: 'ww2-15',
  scenario: 'ww2de',
  title: 'Nebelwerfer',
  description: 'Description.',
  unitPackage: 'de-ww2',
  unitPackagePlayer2: 'us-ww2',
  gameMode: 'domination',
  map: {
    cols: 5,
    rows: 5,
    mountains: ['0,3', '4,1', '4,2'],
    playerStart: [{ col: 1 }, { col: 4 }],
    aiStart: [{ col: 0 }, { col: 3 }],
  },
  productionPointsPerTurn: 20,
}
];

export function getStoryById(id: string): StoryDef | undefined {
  return STORIES.find(s => s.id === id);
}
